### ISSUE TITLE
COM mode datetime option

### ISSUE THREAD

**Issue by HamidAbshahi** [sassoftware/saspy-examples#10]
I need the datetime option to be added to df2sd method when the mode is COM.
Here is the current code in sasiocom.py:

LINE 633 - 634:
DATETIME_NAME = 'DATETIME26.6'
DATETIME_FMT = '%Y-%m-%dT%H:%M:%S.%f'

LINE 682-683:
definition = "'{}'n num informat={} format={}".format(name, DATETIME_NAME, DATETIME_NAME)
formats[name] = lambda x: "'{:{}}'DT".format(x, DATETIME_FMT) if pd.isnull(x) is False else 'NULL'

My proposed changes are adding the following format constants:

DATE_NAME = 'DATE9.'
DATE_FMT = '%d%b%Y'

and updating the code in lines 682-683 to:

if datetimes.get(name, '').lower() == 'date':
    definition = "'{}'n num informat={} format={}".format(name, DATE_NAME, DATE_NAME)
    formats[name] = lambda x: "'{:{}}'D".format(x, DATE_FMT) if pd.isnull(x) is False else 'NULL'
else:
    definition = "'{}'n num informat={} format={}".format(name, DATETIME_NAME, DATETIME_NAME)
    formats[name] = lambda x: "'{:{}}'DT".format(x, DATETIME_FMT) if pd.isnull(x) is False else 'NULL'

Thanks for your attention

**Comment by tomweber-sas** [comment]
Hey @HamidAbshahi , would you mind opening this on the SASPy GitHub site? This is an example notebook repo. If you could use https://github.com/sassoftware/saspy/issues instead, it will be where it needs to be. My first question would be why not use the IOM access method since it supports everything and performs significantly better than COM. COM is missing many features and functionality that the other 3 access methods have, not just his one. Hence the note in the doc: https://sassoftware.github.io/saspy/configuration.html#com
Thanks,
Tom
